### ISSUE TITLE
Head的Connnction 不是close

### ISSUE THREAD

**Issue by zhuxuyang** [MrZhousf/OkHttp3#10]
有时候接口突然调不通了，抓包看到head里的信息如下，connnction 不是close
代码里设置了head的connection也不行
User-Agent: okhttp/3.7.0
Connection: Keep-Alive

**Comment by MrZhousf** [comment]
接口调不通提示什么信息呢？

**Comment by zhuxuyang** [comment]
有toast:  Response: 请检查网络连接是否正常[6]  
也不知道哪里的问题，每次都是替换了你的okhttp3整个包就解决了，我是引用了源码的

**Comment by MrZhousf** [comment]
请采用远程依赖方式引用 compile 'com.zhousf.lib:okhttp3:2.8.9'
