### ISSUE TITLE
发现一个不回调的问题

### ISSUE THREAD

**Issue by wlhjkl** [MrZhousf/OkHttp3#11]
目前测试是版本2.9.0以上：doDownloadFileAsync下载完成后不回调onResponseMain接口，原因找到了在OkMainHandler类第109行，当运行到此处时，条件!BaseActivityLifecycleCallbacks.isActivityDestroyed(downloadMsg.requestTag不成立了，方法内用作判断的callsMap被提前清空了！调试信息和引起此问题的深层次原因如下：
![image](https://user-images.githubusercontent.com/4336142/30513680-05e0a85c-9acd-11e7-8429-35c481f920a4.png)
请查看HttpHelper第104行，异步运行的情况下，在此处提前移除了requestTag
        }finally {
            BaseActivityLifecycleCallbacks.cancel(requestTag,call);
        }
导致上面说的条件不成立，从而无法回调接口。
麻烦作者改一下哈，谢谢

**Comment by MrZhousf** [comment]
很高兴能收到你的问题反馈！
相信你已经阅读过源码并且对源码很了解，你提出的回调问题是这样设计的：
当主动取消请求时：OkHttpUtil.getDefault().cancelRequest(requestTag);
或Activity销毁时会自动取消绑定的所有请求的回调，这样是为了保证页面销毁时若继续回调会出现异常情况。
我们可以试想下，当activity销毁了，异步结果开始回调并操作UI，这时候会出现一些不可预期的问题，虽然OkMainHandler已经进行了异常捕获。
doDownloadFileAsync这个方法是异步下载文件，所以请确保当前页面没被销毁或请求未取消的前提下，结果会正常回调。
综上所述，网络操作时若要确保回调，请控制好异步的问题，建议在结果回调方法中调用取消请求。

**Comment by wlhjkl** [comment]
关键是现在不回调，你的代码是有bug哦，亲，你提前取消了请求的，所以这个接口才没回调！
请查看HttpHelper第104行，异步运行的情况下，在此处提前移除了requestTag
}finally {
BaseActivityLifecycleCallbacks.cancel(requestTag,call);
}
这个是你写的源码里的，不是我写的，Clear？

**Comment by MrZhousf** [comment]
的确是内测版本的一个bug，谢谢你的反馈，bug已修复，请升级版本compile 'com.zhousf.lib:okhttp3:2.9.1'
