### ISSUE TITLE
示例工程app build.gradle配置有问题

### ISSUE THREAD

**Issue by wlhjkl** [MrZhousf/OkHttp3#12]
在Android 7.1上无法调试示例工程

**Comment by MrZhousf** [comment]
这边采用小米手机Android7.0环境测试未发现问题，请问你说的无法调试示例工程具体细节是什么呢？

**Comment by wlhjkl** [comment]
无法使用IDE安装上应用，直接从build目录拿出来apk，用adb命令可以安装，这才造成的无法调试。Android版本7.1.1，MIUI8.5
