### ISSUE TITLE
文件下载后自动重命名有误的问题

### ISSUE THREAD

**Issue by wlhjkl** [MrZhousf/OkHttp3#13]
原始文件名：displayer-0.0.1.1-alpha-2017015164
下载后发现的日志如下：
09-17 00:59:54.911 12600-12750/com.***.displayer D/OkHttpUtil[1505581187664_1562]: 重命名[true]:/storage/emulated/0/***/upgrade/displayer-0.0.1.1-alpha-20170151640.1-alpha-20170151640
09-17 00:59:54.916 12600-12750/com.***.displayer D/OkHttpUtil[1505581187664_1562]: Response: /storage/emulated/0/***/upgrade/displayer-0.0.1.1-alpha-20170151640.1-alpha-20170151640
重命名后的结果不符合预期，对开发使用造成了不便！应该保留原始文件名称不变，若用户提供文件名，再rename成用户需要的文件名～烦劳作者改一下，不胜感激

**Comment by MrZhousf** [comment]
谢谢你的建议，建议已采纳，请更新版本：compile 'com.zhousf.lib:okhttp3:2.9.1'

**Comment by wlhjkl** [comment]
实际测试还是没有改掉这个问题，displayer-0.0.1.1-alpha-2017015164没有扩展名，但是程序自动给我分出了扩展名.0.1.1-alpha-2017015164，这明显是不合理的行为
