### ISSUE TITLE
希望显示一个progressbar，如何去封装

### ISSUE THREAD

**Issue by Dkaishu** [MrZhousf/OkHttp3#15]
每次网络请求的时候显示一个不需要进度的progressbar，可以控制是否显示，怎么去封装合适？

**Comment by MrZhousf** [comment]
“每次网络请求的时候显示一个不需要进度的progressbar，可以控制是否显示”，首先进度条的控制与okhttp库无关，其次你需要说明下你的需求是怎样的，为什么要这样做，我们才好讨论如何封装的问题。

**Comment by Dkaishu** [comment]
应用的场景是这样的：我绝大多数的网络求情都会显示一个正在加载的Dialog或者是Progressbar，表明请求正在进行，且无需显示具体进度，以此我希望每次请求的时候不再去写这个Dialog显示与否的逻辑，而是将其封装在请求里，网络请求的时候显示，取消的时候消失，当然最好是我发起请求的时候可以设置此次请求是否要显示dialog

**Comment by MrZhousf** [comment]
这个你可以在activity/fragment基类里封装网络请求业务和提示框，或采用工具类的方法，这些方法都能达到你的需求。

**Comment by MrZhousf** [comment]
如果你需求我也可以在demo里写一个简单的封装示例

**Comment by Dkaishu** [comment]
万分感谢啊，我估计也很多人会有这个需求，学习了

**Comment by MrZhousf** [comment]
加载框已添加，请参考MainActivity的同步请求、异步请求方法。
