### ISSUE TITLE
怎么添加App拦截器呢?Interceptors

### ISSUE THREAD

**Issue by yangjieK** [MrZhousf/OkHttp3#23]
需求: 添加app的interceptors.

`info=OkHttpUtil.Builder().setInterceptors(new ArrayList<Interceptor>()).build(this).doSync(info);

info = OkHttpUtil.getDefault(this).doSync(info);`

这两句话是否相同

**Comment by MrZhousf** [comment]
框架分为全局配置与自定义配置，自定配置是基于全局配置进行自定设置（相当于继承的概念）。
OkHttpUtil.Builder().setInterceptors(new ArrayList()).build(this).doSync(info);这个是自定配置，可以基于全局配置进行自定义设置。
OkHttpUtil.getDefault(this).doSync(info)；这个是全局配置；
如果你在Application中进行了全局配置，那么上面两句话是相同的。
拦截器在Application全局配置中调用addExceptionInterceptor()方法添加。

**Comment by yangjieK** [comment]
一下懂了. 
需求 :在每一次请求digest authentication, 所以我想要在拦截器中添加. 我需要在Application中添加setInterceptors吗?
