### ISSUE TITLE
每一次访问网络都new OkhttpClient,请教下为什么不用单例?

### ISSUE THREAD

**Issue by yangjieK** [MrZhousf/OkHttp3#25]
OkHttpUtil.java 类中..

![image](https://user-images.githubusercontent.com/4345445/34926395-0bffb3aa-f9ea-11e7-920a-c67ed1e88e8b.png)

### private OkHttpClient.Builder newBuilderFromCopy(){
        OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder()
                .connectTimeout(builder.connectTimeout, TimeUnit.SECONDS)
                .readTimeout(builder.readTimeout, TimeUnit.SECONDS)
                .writeTimeout(builder.writeTimeout, TimeUnit.SECONDS)
                .retryOnConnectionFailure(builder.retryOnConnectionFailure);
        if(builder.cachedDir != null){
            clientBuilder.cache(new Cache(builder.cachedDir,builder.maxCacheSize));
        }
        if(null != builder.networkInterceptors && !builder.networkInterceptors.isEmpty())
            clientBuilder.networkInterceptors().addAll(builder.networkInterceptors);
        if(null != builder.interceptors && !builder.interceptors.isEmpty())
            clientBuilder.interceptors().addAll(builder.interceptors);
        if(null != builder.cookieJar)
            clientBuilder.cookieJar(builder.cookieJar);
        return clientBuilder;
    }

BaseHelper.java 类中
### private OkHttpClient initHttpClient(HelperInfo helperInfo, CookieJar cookieJar){
        OkHttpClient.Builder clientBuilder = helperInfo.getClientBuilder();
        clientBuilder.protocols(Arrays.asList(Protocol.SPDY_3, Protocol.HTTP_1_1));
        clientBuilder.addInterceptor(NO_NETWORK_INTERCEPTOR);
        clientBuilder.addNetworkInterceptor(NETWORK_INTERCEPTOR);
        if(helperInfo.isGzip()){
            clientBuilder.addInterceptor(new GzipRequestInterceptor());
        }
        if(null != cookieJar)
            clientBuilder.cookieJar(cookieJar);
        if(httpInfo == null || httpInfo.getUrl() == null)
            return clientBuilder.build();
        try {
            URI uri = new URL(httpInfo.getUrl()).toURI();
            if("https".equals(uri.getScheme())){
                if(helperInfo.getHttpsCertificateStream() == null){
                    setDefaultSslSocketFactory(clientBuilder);
                }else{
                    setSslSocketFactory(clientBuilder);
                }
            }
        } catch (URISyntaxException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return clientBuilder.build();
    }

该代码每一次网络都会new okhttpclient实例, 为啥不用单例优化,防止oom?

**Comment by MrZhousf** [comment]
![image](https://user-images.githubusercontent.com/18730574/34932238-0a96b59a-fa0d-11e7-9967-015fbb56858a.png)

**Comment by yangjieK** [comment]
defaultClient 是httpclient赋值的. 
### private OkHttpClient initHttpClient(HelperInfo helperInfo, CookieJar cookieJar){
        OkHttpClient.Builder clientBuilder = helperInfo.getClientBuilder();
        clientBuilder.protocols(Arrays.asList(Protocol.SPDY_3, Protocol.HTTP_1_1));
        clientBuilder.addInterceptor(NO_NETWORK_INTERCEPTOR);
        clientBuilder.addNetworkInterceptor(NETWORK_INTERCEPTOR);
        if(helperInfo.isGzip()){
            clientBuilder.addInterceptor(new GzipRequestInterceptor());
        }
        if(null != cookieJar)
            clientBuilder.cookieJar(cookieJar);
        if(httpInfo == null || httpInfo.getUrl() == null)
            return clientBuilder.build();
        try {
            URI uri = new URL(httpInfo.getUrl()).toURI();
            if("https".equals(uri.getScheme())){
                if(helperInfo.getHttpsCertificateStream() == null){
                    setDefaultSslSocketFactory(clientBuilder);
                }else{
                    setSslSocketFactory(clientBuilder);
                }
            }
        } catch (URISyntaxException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        return clientBuilder.build();
    }


 clientBuilder.build(); 该完成每一次都会生成 new OkHttpClient

**Comment by MrZhousf** [comment]
感谢你的回复。你说是对的，的确每次请求前都会 new OkHttpClient，但是在用的时候会判断OkHttpClient单例是否存在，若存在就采用单例请求，若不存在就采用刚才new的OkHttpClient进行请求。
这样的设计也就是说每次请求都会携带一个新的OkHttpClient给HttpHelper，具体调用由HttpHelper负责管理。
所以我们在调用时采用OkHttpUtil.getDefault(this).doAsync();这个方式则是单例请求，这种方式也是推荐使用的，因为其支持单例请求、请求结束后自动释放资源等。

**Comment by MrZhousf** [comment]
wow，确实如你所说，这个应该是迭代过程中出现的一个bug，你是个明智的人，非常感谢你的指正，这边已经修改了，请更新下。

**Comment by yangjieK** [comment]
@MrZhousf  可否留个邮箱,方便不明白也可以请教.

**Comment by MrZhousf** [comment]
QQ 424427633
