### ISSUE TITLE
请求上传文件,返回结果是流. 如何调用?

### ISSUE THREAD

**Issue by yangjieK** [MrZhousf/OkHttp3#26]
需求: 我上传一个文件,返回的也是一个文件.  这时没有api可以调用

**Comment by MrZhousf** [comment]
很感谢你提出的问题，目前框架返回的都是处理过后的字符串，我这边会将返回的ResponseBody 封装到返回结果里，调用层可以采用ResponseBody.byteStream()、 ResponseBody .charStream()、  ResponseBody.bytes()、ResponseBody..string()获取接口返回信息。

**Comment by yangjieK** [comment]
感谢您的回复,期待

**Comment by MrZhousf** [comment]
compile 'com.zhousf.lib:okhttp3:2.9.5.3'
新版本已经支持，用法请参考示例：
![image](https://user-images.githubusercontent.com/18730574/34970421-47750dd4-faaf-11e7-8540-403498753f98.png)
