### ISSUE TITLE
上传文件是 .db ,则上传接口失败

### ISSUE THREAD

**Issue by yangjieK** [MrZhousf/OkHttp3#27]
上传接口
上传文件.db文件,则上传文件失败,则需提供 二进制流类型
![image](https://user-images.githubusercontent.com/4345445/35024014-3e606fee-fb78-11e7-8769-94572813bf90.png)

MediaTypeUtil.java 类
### public static MediaType fetchFileMediaType(String url,String requestEncoding){
        if(!TextUtils.isEmpty(url) && url.contains(".")){
            String extension = url.substring(url.lastIndexOf(".") + 1);
            if("png".equals(extension)){
                extension = "image/png";
            }else if("jpg".equals(extension)){
                extension = "image/jpg";
            }else if("jpeg".equals(extension)){
                extension = "image/jpeg";
            }else if("gif".equals(extension)){
                extension = "image/gif";
            }else if("bmp".equals(extension)){
                extension = "image/bmp";
            }else if("tiff".equals(extension)){
                extension = "image/tiff";
            }else if("ico".equals(extension)){
                extension = "image/ico";
            }else{
                extension = ContentType.FORM_DATA;
            }
            return MediaType.parse(extension+requestEncoding);
        }
        return null;
    }

### 我实现的上传文件的方法如下 :
HttpInfo info = HttpInfo.Builder().addUploadFile("fileToUpload", BackupDatabaseHelp.getDBPath())
                .addParam("account_id", server_account_id + "")
                .addParam("rt", "1").setUrl(url)
                .setNeedResponse(true).build();
        OkHttpUtil.getDefault().doUploadFileSync(info);

**Comment by yangjieK** [comment]
### 我实现的上传文件的方法如下 :
HttpInfo info = HttpInfo.Builder().addUploadFile("fileToUpload", BackupDatabaseHelp.getDBPath())
                .addParam("account_id", server_account_id + "")
                .addParam("rt", "1").setUrl(url)
                .setNeedResponse(true).build();
        OkHttpUtil.getDefault().doUploadFileSync(info);

**Comment by MrZhousf** [comment]
版本已更新：compile ('com.zhousf.lib:okhttp3:2.9.5.5')
扩展了上传文件API；
![image](https://user-images.githubusercontent.com/18730574/35037423-72bc249c-fbb2-11e7-9e6f-cc0952ca77cb.png)
