### ISSUE TITLE
不做任何请求，直接OkHttpUtil.getDefault().getDefaultClient() null异常是什么回事？

### ISSUE THREAD

**Issue by wuting1992** [MrZhousf/OkHttp3#29]
不做任何请求是，使用OkHttpUtil.getDefault().getDefaultClient()调用里面的方法，抛null异常是什么回事。

**Comment by MrZhousf** [comment]
compile 'com.zhousf.lib:okhttp3:2.9.6'，问题已修复，请更新至最新版。谢谢你提出的问题！
