### ISSUE TITLE
无法持久化cookie

### ISSUE THREAD

**Issue by lzp-punk** [MrZhousf/OkHttp3#3]
楼主，你的网络请求是每次都要调用OkHttpClient.Builder.build()然后新建了一个okhttpclient出来,这样无法对cookie持久化操作。

**Comment by MrZhousf** [comment]
//Cookie持久化示例
OkHttpUtil okHttpUtil = OkHttpUtil.Builder()
            .setCacheLevel(FIRST_LEVEL)
            .setConnectTimeout(25).build(this);
//一个okHttpUtil即为一个网络连接
okHttpUtil.doGetAsync(
                HttpInfo.Builder().setUrl(url).build(),
                new CallbackOk() {
                    @Override
                    public void onResponse(HttpInfo info) throws IOException {
                        if (info.isSuccessful()) {
                            String result = info.getRetDetail();
                            resultTV.setText("异步请求："+result);
                        }
                    }
                });

**Comment by lzp-punk** [comment]
作者，我看过你的源码，OkHttpUtil.Builder().build()是会新建一个okhttpclient出来的，如果每一次网络请求都要调用OkHttpUtil.Builder().build()，不同的网络请求在不同的okhttpclient中执行，cookie怎么持久化，我试过你持久化的例子，不同activity的网络请求，cookie持久化不了。

**Comment by MrZhousf** [comment]
明白你的意思了，我之前做过爬虫、模拟等操作需要cookie持久化，你可以先保存请求的okhttputil对象到activity基类的静态变量中，其他的activity使用该变量时先进行非空判断后再操作即可。
我会在下一个版本对全局的持久化cookie进行支持，版本迭代后会给你email，请关注动态。

**Comment by MrZhousf** [comment]
已支持Cookie持久化全局配置，版本已迭代至1.7，请测试。

**Comment by lzp-punk** [comment]
刚刚看了你的代码，没有测试过，不过创建时调用这个方法到okhttpclient.builder().addcookieJar()应该可以持久化，我自己就另外添加了获取单例okhttputil的方法，方便调用

**Comment by lzp-punk** [comment]
如何主动去取消一个请求

**Comment by MrZhousf** [comment]
请了解下BaseActivityLifecycleCallbacks
