### ISSUE TITLE
Could not resolve com.zhousf.lib:okhttp3:2.9.6

### ISSUE THREAD

**Issue by dgutkai** [MrZhousf/OkHttp3#31]
在引用库的时候，出现下面的错误要怎么解决？
> Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.zhousf.lib:okhttp3:2.9.6.
Could not resolve com.zhousf.lib:okhttp3:2.9.6.
Required by:
    project :app
 > Could not resolve com.zhousf.lib:okhttp3:2.9.6.
    > Could not get resource 'https://jcenter.bintray.com/com/zhousf/lib/okhttp3/2.9.6/okhttp3-2.9.6.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/zhousf/lib/okhttp3/2.9.6/okhttp3-2.9.6.pom'.
                   > jcenter.bintray.com: nodename nor servname provided, or not known

我的Build.gradle如下，其他的包都能下载的了，就这个OKHTTP下载不了。：
> dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.zhousf.lib:okhttp3:2.9.6'
}

**Comment by MrZhousf** [comment]
com.zhousf.lib:okhttp3:2.9.7
