### ISSUE TITLE
请求Tag与Activity生命周期管理

### ISSUE THREAD

**Issue by amber-yi** [MrZhousf/OkHttp3#35]
在我做项目的时候，发现有一个播放视频的界面A，当finish的时候并没有立即调用onDestroy方法，而我启动请求的方式是 OkHttpUtil.getDefault(mActivity)方式，因此存在一个问题，当A被finish后，立马重新进入，这时A界面的所有请求将被取消（此时其实有两个A，一个正等待destory，一个刚被创建，因为BaseActivityLifecycleCallbacks里面监听了activity的生命周期，并且在onActivityDestroyed回调里面取消此activity的所有请求）
建议在添加与移除请求的时候，不是通过activity.getClass().getName()而是通过activity.toString()，将activity的内存地址作为键值保存。

**Comment by MrZhousf** [comment]
谢谢你的建议，已做修改
compile 'com.zhousf.lib:okhttp3:2.9.7'
