### ISSUE TITLE
断点下载的后续处理

### ISSUE THREAD

**Issue by countingStarZhou** [MrZhousf/OkHttp3#8]
你好，

     我刚在跟你的代码，断点下载的后续处理，比如暂停啥的，没逻辑了，具体是这里：

        ResultInterceptor ResultInterceptor = new ResultInterceptor()  public HttpInfo intercept(HttpInfo info)里面方法没有处理

           期待回复

**Comment by MrZhousf** [comment]
你好，断点下载逻辑DownUpLoadHelper文件的downloadingFile方法，如有问题请通过qq沟通，这样方便问题的及时反馈，谢谢！
